### PR TITLE
CakePHP 3.6 compatibility

### PR DESCRIPTION
**Pull request by iiriya**

### CODE REVIEW

**Comment by ADmad** [comment]
Why have you removed the error logging code?

**Comment by iiriya** [comment]
I'm not. Just changed $this->config to $this->setConfig/$this->getConfig
Maybe I took a wrong version

**Comment by ADmad** [comment]
Please use the `dev` branch and add updates to that. Also be please test the updated code in your app as there's no test coverage yet for the plugin :)

**Comment by iiriya** [comment]
Sorry, I'll use the dev brench.
I've tested the config methods changes on my apps and it works on CakePHP 3.6.

**Comment by ADmad** [comment]
No problem. The dev branch has additional feature additions and refactoring hence my suggestion to test it out :).

**Comment by ava007** [comment]
I've tested this change and it works.  see https://www.41max.com

**Comment by ADmad** [comment]
`0.4.0` released with updated deprecated methods.

**Pull request closed without merging**
